### ISSUE TITLE
PostgreSQL ユーザー作成エラーにて停止

### ISSUE THREAD

**Issue by endomame** [farend/redmine-ubuntu-ansible#2]
下記エラーが発生しインストール停止
TASK [pg : PostgreSQL ユーザー作成] **************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

下記設定にて回避
https://github.com/ansible/ansible/issues/16048

**Comment by vividtone** [comment]
7460414 で修正しました。
ご指摘ありがとうございました。
